{% set version = "1.6-0.15" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rtriangle
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RTriangle_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RTriangle/RTriangle_{{ version }}.tar.gz
  sha256: b1c5c5c7152c1b28d4a46c838ffdda28a2470152fe74814d9d02b908feed4306

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('m2w64_c') }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('RTriangle')"           # [not win]
    - "\"%R%\" -e \"library('RTriangle')\""  # [win]

about:
  home: https://github.com/davidcsterratt/RTriangle, http://www.cs.cmu.edu/~quake/triangle.html
  dev_url: https://github.com/davidcsterratt/RTriangle
  license: CC-BY-NC-SA-4.0
  summary: "This is a port of Jonathan Shewchuk's Triangle library to R. From his description: \"Triangle generates exact Delaunay triangulations, constrained Delaunay triangulations, conforming Delaunay triangulations, Voronoi diagrams, and high-quality triangular meshes. The latter can be generated with no small or large
    angles, and are thus suitable for finite element analysis.\""
  license_family: CC
  license_file:
    - LICENSE-CC-BY-NC-SA-4
    - LICENSE.note

extra:
  recipe-maintainers:
    - conda-forge/r
